Import('env')

env.install(env.compileAndJar('agent.jar', 'agent', 
    libs=[env['CLOJURE'],
        env.File('$BUILD_DIR/argparser.jar'),
        env.File('$EXTLIB/ring-1.1.8.jar'),
        env.File('$EXTLIB/ring-jetty-adapter-1.1.8.jar'),
        env.File('$EXTLIB/compojure-1.1.5.jar'),
        env.File('$EXTLIB/data.json-0.2.2.jar'),
        env.File('$EXTLIB/java.jdbc-0.3.0-alpha5.jar'),
        env.File('$EXTLIB/mysql-connector-java-5.1.26-bin.jar'),
        env.File('$BUILD_DIR/logging.jar'),
        env.File('$BUILD_DIR/utilities.jar'),   
        env.File('$BUILD_DIR/monitor.jar')               
    ], 
    standalone=True, manifest={'Main-Class': 'agent.main'}))

env.install(env.compileAndJar('monitor.jar', 'monitor', 
    libs=[env['CLOJURE'],
        env.File('$BUILD_DIR/utilities.jar'),
    ], 
    standalone=True, manifest={'Main-Class': 'monitor.main'}))

env.install(env.compileAndJar('9sea_unittest.jar', 'unittest',
    libs=[env['CLOJURE'], 
        env.File('$EXTLIB/tools.cli-0.2.2.jar'),
        env.File('$BUILD_DIR/testing.jar'),
        env.File('$BUILD_DIR/agent.jar'),
        ],

    standalone=True, manifest={'Main-Class': 'unittest.main'}))
env.install(env.compileAndJar('9sea_smoketest.jar', 'smoketest',
    libs=[env['CLOJURE'], 
        env.File('$EXTLIB/tools.cli-0.2.2.jar'),
        env.File('$BUILD_DIR/testing.jar'),
        env.File('$BUILD_DIR/utilities.jar'),
        env.File('$BUILD_DIR/monitor.jar'),
        env.File('$EXTLIB/data.json-0.2.2.jar'),
        
    ],
    standalone=True, manifest={'Main-Class': 'smoketest.main'}))